_target_: src.datamodules.opg_datamodule.OPGDataModule

input_pxl: 504
data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
test_batch_size: 64
train_val_test_split: [5451, 1363, 2218]
num_workers: 4
pin_memory: False
IS_RESNET: False
