_target_: src.datamodules.opg_datamodule.OPGDataModule

input_pxl: 420
data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
test_batch_size: 64
train_val_test_split: [6751, 1134, 1148]
num_workers: 4
pin_memory: False
IS_RESNET: False
